name: Trigger auto deployment for container-app-7fy7selwx363k

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-7fy7selwx363k-AutoDeployTrigger-358dc050-81f2-4ca5-ae3a-6d9d02b94484.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP7FY7SELWX363K_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP7FY7SELWX363K_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP7FY7SELWX363K_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP7FY7SELWX363K_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP7FY7SELWX363K_REGISTRY_PASSWORD }}
          containerAppName: container-app-7fy7selwx363k
          resourceGroup: todoapptest85ce
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


